package controller.checkout;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import controller.client.ClientView;
import model.booking.Booking;
import model.user.User;
import services.ClientServices;
import services.UserService;

import javax.swing.*;
import java.util.Date;


public class CheckoutView extends javax.swing.JFrame {

    /**
     * Creates new form CheckoutView
     */
    private Booking currentBooking;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel changeLabel;
    private javax.swing.JTextField cvcTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTf;
    private javax.swing.JTextField numberTf;
    private javax.swing.JButton paymentBtn;
    private javax.swing.JComboBox<String> paymentCombo;
    private java.awt.List reciptList;

    public CheckoutView(Booking booking) {
        currentBooking = booking;
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckoutView(new Booking(1, new Date(), 1, 2, 22, 23, "ACE-2", "rafd47@my.yorku.ca")).setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        paymentCombo = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();
        paymentBtn = new javax.swing.JButton();
        reciptList = new java.awt.List();
        jLabel7 = new javax.swing.JLabel();
        changeLabel = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        numberTf = new javax.swing.JTextField();
        cvcTf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        if (currentBooking != null) {
            User user = UserService.getInstance().getUserByEmail(currentBooking.getEmail());
            reciptList.add("Role    " + user.getCredentials().getType());
            reciptList.add("Email   " + user.getCredentials().getLogin());
            reciptList.add("Hours   " + currentBooking.getTotalHours());
            reciptList.add("Deposit for 1 hour:    " + currentBooking.getCost() / currentBooking.getTotalHours());
        }

        paymentCombo.addItem("Credit Card");
        paymentCombo.addItem("Debit Card");
        paymentCombo.addItem("Mobile Payment");

        paymentCombo.addActionListener(e -> {
            if (paymentCombo.getSelectedItem().equals("Mobile Payment")) {
                cvcTf.setVisible(false);
                changeLabel.setText("Please Enter your Mobile Number");

                numberTf.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
            } else {
                cvcTf.setVisible(true);
                changeLabel.setText("Card Holder Name");
                nameTf.setVisible(true);
                numberTf.setVisible(true);
                jLabel9.setVisible(true);
                jLabel10.setVisible(true);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Deposit");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("How you want to pay?");

        backBtn.setBackground(new java.awt.Color(0, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        paymentBtn.setBackground(new java.awt.Color(0, 153, 153));
        paymentBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        paymentBtn.setForeground(new java.awt.Color(255, 255, 255));
        paymentBtn.setText("Payment");
        paymentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Recipt");

        changeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        changeLabel.setForeground(new java.awt.Color(51, 51, 51));
        changeLabel.setText("Card Holder Name");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Card Number");

        numberTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTfActionPerformed(evt);
            }
        });

        cvcTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvcTfActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("CVC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(backBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(paymentCombo, 0, 192, Short.MAX_VALUE)
                                                                .addComponent(jLabel6)
                                                                .addComponent(changeLabel)
                                                                .addComponent(nameTf))
                                                        .addComponent(jLabel9)
                                                        .addComponent(numberTf, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel10)
                                                        .addComponent(cvcTf, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(reciptList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap(46, Short.MAX_VALUE)
                                                .addComponent(paymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(paymentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(changeLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(numberTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cvcTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(reciptList, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(paymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(false);
                new ClientView(UserService.getInstance().getUserByEmail(currentBooking.getEmail())).setVisible(true);
            }
        });


    }//GEN-LAST:event_backBtnActionPerformed

    private void paymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBtnActionPerformed
        // TODO add your handling code here:
        if (paymentCombo.getSelectedItem().equals("Mobile Payment")) {
            String phone = nameTf.getText();
            if (phone.equals("")) {
                JOptionPane.showMessageDialog(null, "All Details are Required!!!");
                return;
            }
            boolean isBooked = ClientServices.getInstance().bookParkingSpace(currentBooking);
            if (isBooked) {
                JOptionPane.showMessageDialog(null, "Your Booked Space Successfully");
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        setVisible(false);
                        new ClientView(UserService.getInstance().getUserByEmail(currentBooking.getEmail())).setVisible(true);
                    }
                });
            } else {
                JOptionPane.showMessageDialog(null, "There is some issue with booking");
            }

        } else {
            String name = nameTf.getText();
            String card = numberTf.getText();
            String cvc = cvcTf.getText();
            if (name.equals("") || card.equals("") || cvc.equals("")) {
                JOptionPane.showMessageDialog(null, "All Details are Required!!!");
                return;
            }
            boolean isBooked = ClientServices.getInstance().bookParkingSpace(currentBooking);
            if (isBooked) {
                JOptionPane.showMessageDialog(null, "You Booked Space Successfully");
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        setVisible(false);
                        new ClientView(UserService.getInstance().getUserByEmail(currentBooking.getEmail())).setVisible(true);
                    }
                });
            } else {
                JOptionPane.showMessageDialog(null, "There is some issue with booking");
            }


        }

    }//GEN-LAST:event_paymentBtnActionPerformed

    private void numberTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTfActionPerformed

    private void cvcTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvcTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvcTfActionPerformed
    // End of variables declaration//GEN-END:variables
}
